---
abstract: 'Turns a quoted string into a single line'
author:
  - "Robert 'phaylon' Sedlacek <rs@474.at>"
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Syntax-Feature-Ql
no_index:
  directory:
    - t/
provides:
  Syntax::Feature::Ql:
    file: lib/Syntax/Feature/Ql.pm
    version: 0.001000
requires:
  B::Hooks::EndOfScope: 0.09
  Devel::Declare: 0.006007
  Devel::Declare::Context::Simple: 0
  Sub::Install: 0.925
  Syntax::Feature::Simple::V2: 0
  aliased: 0
  namespace::clean: 0
  strictures: 1
  syntax: 0.003
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Syntax-Feature-Ql
  homepage: https://github.com/phaylon/Syntax-Feature-Ql/wiki
  repository: git://github.com/phaylon/Syntax-Feature-Ql.git
version: 0.001000
x_authority: cpan:PHAYLON
